import Noty from 'noty';
import jQuery from 'jquery';
import 'arrive';
import 'noty/lib/noty.css';
import 'noty/lib/themes/relax.css';

import type { RequestPayload } from '../types/domain';

// Runtime presence of the GM APIs is guaranteed by the `@grant` header
// generated by `scripts/release.js`, so the unsafe casts below are safe.
const gms = {
  openInTab: (GM_openInTab ?? (GM as any).openInTab) as (url: string, options?: object) => void,
  setValue: (GM_setValue ?? (GM as any).setValue) as (key: string, value: string | number) => void,
  getValue: (GM_getValue ?? (GM as any).getValue) as (key: string, defaultValue?: string | number) => unknown,
  deleteValue: (GM_deleteValue ?? (GM as any).deleteValue) as (key: string) => void,
  addStyle: (GM_addStyle ?? (GM as any).addStyle) as (css: string) => void,
  setClipboard: (GM_setClipboard ?? (GM as any).setClipboard) as (text: string) => void,
  xmlhttpRequest: (GM_xmlhttpRequest ?? (GM as any).xmlHttpRequest) as (
    details: Record<string, unknown>,
  ) => void,
};

const $ = jQuery.noConflict(true);

Noty.overrideDefaults({
  // layout: 'bottomRight',
  theme: 'relax',
  visibilityControl: true,
  timeout: 10000,
});
Noty.setMaxVisible(999999999);

interface GmResponse {
  status: number;
  responseText: string;
}

export default class MonkeyKernel {
  /** Open a new tab via the userscript manager. */
  static openTab(url: string, options?: object): void {
    return gms.openInTab(url, options);
  }

  /** Persist a value in the userscript manager storage. */
  static setValue(key: string, value: string | number): void {
    return gms.setValue(key, value);
  }

  /** Read a value from the userscript manager storage. */
  static getValue(key: string, defaultValue?: string | number): unknown {
    return gms.getValue(key, defaultValue);
  }

  /** Remove a value from the userscript manager storage. */
  static deleteValue(key: string): void {
    return gms.deleteValue(key);
  }

  /** Inject a `<style>` tag into the page. */
  static addStyle(css: string): void {
    return gms.addStyle(css);
  }

  /** Copy text to the system clipboard. */
  static setClipboard(text: string): void {
    return gms.setClipboard(text);
  }

  /**
   * Perform a cross-origin request through the userscript manager and parse
   * the response as JSON. `query` is appended to the URL, `body` is sent as
   * URL-encoded form data.
   */
  static requestJSON(request: RequestPayload): Promise<unknown> {
    const { query, body, method = 'GET' } = request;
    const url = query ? [request.url, $.param(query)].join('?') : request.url;
    const data = body ? $.param(body) : undefined;

    return new Promise((resolve, reject) => {
      gms.xmlhttpRequest({
        method,
        url,
        data,
        onerror: (err: unknown) => {
          console.debug('[GM:Kernel]Request: %o, Response error: %o', request, err);
          reject(err);
        },
        onload: (response: GmResponse) => {
          if (response.status >= 300) {
            return reject(response.responseText);
          }

          try {
            const res = JSON.parse(response.responseText);
            console.debug('[GM:Kernel]Request: %o, Response success: %o', request, res);
            return resolve(res);
          } catch (e) {
            console.debug('[GM:Kernel]Request: %o, Response error: %o', request, response);
            return reject(e);
          }
        },
      });
    });
  }

  /** Show a Noty toast notification. */
  static notify(text: string, type: 'alert' | 'error' | 'success' = 'alert', notyOptions: Record<string, unknown> = {}): void {
    new Noty(Object.assign({ text, type }, notyOptions)).show();
  }

  /** Register a handler for elements that appear later in the DOM (arrive). */
  static arrive(selector: string, handler: (el: HTMLElement) => void): void {
    $(document).arrive(selector, handler);
  }
}

export { $, jQuery, Noty };
